[project]
name = "musigree"
version = "1.0.0"
description = "Interactive visualization of the Discogs database"
authors = [
    { name = "Andy Radburn", email = "andy.radburn@outlook.com" },
    { name = "Josiah Wolf Oberholtzer", email = "josiah.oberholtzer@gmail.com" },
]
license = { text = "MIT" }
requires-python = ">=3.13,<4.0"  # Changed to a more general requirement.
readme = "README.md"

dependencies = [
    "fastapi==0.116.1",
    "sqlalchemy[asyncio]==2.0.43",
    "psycopg[binary]~=3.2.9",
    "aiosqlite~=0.21.0",
    "pydantic~=2.11.7",
    "pydantic-settings~=2.10.1",
    "luigi~=3.6.0",
    "sortedcontainers~=2.4.0",
    "deepdiff==8.6.0",
    "RapidFuzz~=3.12.2",
    "retrying~=1.4.2",
    "requests~=2.32.4",
    "python-dateutil~=2.9.0.post0",
    "toolz~=1.0.0",
    "Unidecode~=1.3.8",
    "python-dotenv~=1.1.1",
    "uvicorn~=0.35.0",
    "httpx~=0.28.1",
    "jinja2~=3.1.6",
    "asyncio-atexit~=1.0.1",
    "asyncstdlib~=3.13.1",
]

[project.urls]
Repository = "https://github.com/aradburn/musigree"
Homepage = "https://github.com/aradburn/musigree"
Issues = "https://github.com/aradburn/musigree/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

[tool.uv]
dev-dependencies = [
    "pg-temp>=0.9.1,<1.0.0",
    "fakeredis~=2.31.0",
    "pytest~=8.4.1",
    "pytest-mock~=3.14.1",
    "pytest-asyncio~=1.1.0",
    "pytest-cov~=6.2.1",
    "mypy~=1.17.1",
    "memray>=1.17.2,<2.0.0",
    "pytest-memray>=1.7.0,<2.0.0",
    "sortedcontainers-stubs~=2.4.3",
    "types-requests~=2.32.4.20250611",
    "types-python-dateutil~=2.9.0.20250516",
    "locust~=2.37.11",
    "ruff>=0.12.9",
    "hatchling>=1.27.0",
    "yappi>=1.6.10",
]

[tool.mypy]
python_version = "3.13"
warn_return_any = true
disallow_untyped_defs = true

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["B"]


